[bindings.kotlin]
package_name = "org.openswap"
cdylib_name = "openswap_ffi"

[bindings.swift]
module_name = "Openswap"
cdylib_name = "Openswap_ffi"

[bindings.csharp]
namespace = "Openswap.Native"
global_methods_class_name = "Openswap"
access_modifier = "public"
cdylib_name = "openswap_ffi"
